# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.8
  - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

env:
  - AWS_REGION=eu-west-1 AWS_DEFAULT_REGION=eu-west-1
